# -*- coding: utf-8 -*-
"""生成 ECDSA P-256 密钥对(OTA 固件签名用)

- 私钥 private_key.pem:**只留在本机,务必不要上传**(已在 .gitignore)
- 公钥 ../App/Core/Inc/ecc_pubkey.h:64 字节裸公钥(x||y),编译进固件供验签

用法:
    pip install ecdsa
    python keygen.py          # 首次生成;已存在则仅重新导出公钥头
"""
import os
import sys

try:
    from ecdsa import SigningKey, NIST256p
except ImportError:
    sys.exit("缺少 ecdsa 库,先执行: pip install ecdsa")

PRIV_PEM = "private_key.pem"
PUB_HEADER = os.path.join("..", "App", "Core", "Inc", "ecc_pubkey.h")


def load_or_create():
    if os.path.exists(PRIV_PEM):
        print(f"私钥已存在,复用: {PRIV_PEM}")
        with open(PRIV_PEM) as f:
            return SigningKey.from_pem(f.read())
    sk = SigningKey.generate(curve=NIST256p)
    with open(PRIV_PEM, "w") as f:
        f.write(sk.to_pem().decode())
    print(f"已生成新私钥: {PRIV_PEM}  (请妥善保管,勿上传)")
    return sk


def export_pubkey(sk):
    pub = sk.get_verifying_key().to_string()   # 64 字节: x[32] || y[32]
    assert len(pub) == 64

    lines = [
        "#ifndef __ECC_PUBKEY_H",
        "#define __ECC_PUBKEY_H",
        "",
        "#include <stdint.h>",
        "",
        "/* Auto-generated by Host/keygen.py. Do not edit. ECDSA P-256 public key (x||y, 64 bytes) */",
        "static const uint8_t g_ecc_pubkey[64] = {",
    ]
    for i in range(0, 64, 8):
        row = ", ".join(f"0x{b:02X}" for b in pub[i:i + 8])
        lines.append(f"    {row},")
    lines += ["};", "", "#endif /* __ECC_PUBKEY_H */", ""]

    os.makedirs(os.path.dirname(PUB_HEADER), exist_ok=True)
    with open(PUB_HEADER, "w") as f:
        f.write("\n".join(lines))
    print(f"已导出公钥头: {PUB_HEADER}")


if __name__ == "__main__":
    export_pubkey(load_or_create())
    print("完成。把 ecc_pubkey.h 随 App 一起编译即可。")
